dist: precise
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
language: java
jdk:
  - oraclejdk8
install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: ./mvnw test -B -pl !demo-original
