version: '{build}'

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0 

build_script:
  - .\mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
test_script:
  - .\mvnw test -B -pl !demo-original
